### ISSUE TITLE
I had to restart Emacs. Worth mentioning?

### ISSUE THREAD

**Issue by danrobi11** [karthink/dired-hist#1]
Hi.
The user might need to restart Emacs. It wasnt working here with `load-file` I had to restart Emacs.
Do you think its worth mentioning in the `README`?

Anyhow, Thank you for your project.

**Comment by DivineDominion** [comment]
I cloned the repo and then used this:

```elisp
(use-package dired-hist
  :load-path "~/.emacs.d/src/dired-hist"
  :hook (dired-mode . dired-hist-mode)
  :bind
  (:map dired-mode-map
        ("l". #'dired-hist-go-back)
        ("r" . #'dired-hist-go-forward)))
```

Executing that worked right away.

So the `with-eval-after-load` approach might be a bit odd for quick testing. Using hooks works as well FWIW

**Comment by danrobi11** [comment]
@DivineDominion Yep that's working. Thanks for  sharing.

**Comment by karthink** [comment]
@danrobi11 The eval-after-load ordering was wrong, thanks for testing. Basically `dired-hist-mode` needs to be already loaded before opening your first dired buffer so it can register this buffer in the history. I simplified the usage instructions.

**Comment by danrobi11** [comment]
@karthink Perfect. Thank you. Closing.
